version: 2
jobs:
  build:
    machine: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "ce:60:dc:87:cd:91:06:1c:e5:4d:f6:bf:c5:02:a5:61"
      - checkout
      - run:
          name: Set NODE_NO_WARNINGS variable
          command: export NODE_NO_WARNINGS=1
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build -t nicolaszelarayan/reciclarg2023:$CIRCLE_SHA1 .
      - run: docker push nicolaszelarayan/reciclarg2023:$CIRCLE_SHA1
      - run: ssh -o StrictHostKeyChecking=no -t -t nicolas_zelarayan@reciclarg.cloud "cd /home/nicolas_zelarayan/reciclarg_react/Reciclarg && sudo git pull"
      - run: ssh -o StrictHostKeyChecking=no -t -t nicolas_zelarayan@reciclarg.cloud "cd /home/nicolas_zelarayan/reciclarg_react/Reciclarg && sudo npm install"
      - run: ssh -o StrictHostKeyChecking=no -t -t nicolas_zelarayan@reciclarg.cloud "cd /home/nicolas_zelarayan/reciclarg_react/Reciclarg && sudo npm run build"
      - run: ssh -o StrictHostKeyChecking=no -t -t nicolas_zelarayan@reciclarg.cloud "cd /home/nicolas_zelarayan/reciclarg_react/Reciclarg && sudo docker build -t nicolaszelarayan/reciclarg2023:$CIRCLE_SHA1 -f Dockerfile ."
      - run: ssh -o StrictHostKeyChecking=no -t -t nicolas_zelarayan@reciclarg.cloud "sudo docker run -p 8082:80 -d nicolaszelarayan/reciclarg2023:$CIRCLE_SHA1"
