name: Deploy to Nginx Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        project_id: ${{ env.PROJECT_ID }}
        credentials: ${{ env.CREDENTIALS }}
    - name: Install dependencies
      run: npm install
    - name: Build
      run: npm run build
    - name: Deploy to GCP
      run: |
        gcloud app deploy

env:
  PROJECT_ID:  helpful-kit-383103
  CREDENTIALS: ${{ secrets.GCP_CREDENCIALES }}
  HOST: reciclarg.cloud
  USERNAME: nicolas_zelarayan
  PASSWORD: ${{ secrets.SERVER_PASSWORD }}
  
  script: |
        cd /var/www/html
        git clone https://github.com/Los-Chiperos/Reciclarg.git
        cd Reciclarg
        npm install
        sudo systemctl restart nginx
